accounts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('address/', login_required(views.AddressListView.as_view()), name='address_list'),
    path('address/<int:pk>/', login_required(views.AddressDetailView.as_view()), name='address_detail'),
    path('address/create', views.create_address, name='create_Address'),
    path('password-reset/', views.CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-done/',
         views.CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/',
         views.CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('address/delete/<int:pk>/', views.delete_address, name="delete_address"),
    path('address/edit/<int:pk>/', views.edit_address, name='edit_address'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('minus/<int:product_id>/', views.cart_minus, name='cart_minus'),
    path('plus/<int:product_id>/', views.cart_plus, name='cart_plus'),
]

onlineShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('delivery/', include('delivery.urls')),
    path('', include('django_prometheus.urls')),

]

order/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', login_required(views.order_create), name='order_create'),
    path('<int:pk>/', login_required(views.OrderDetailView.as_view()), name='detail'),
    path('', login_required(views.OrderListView.as_view()), name='order_list'),
    path('payment/<int:order_id>/', views.payment, name='payment'),
    path('delete/<int:pk>', views.delete_order, name='delete_order'),
    path('verify/', views.verify, name='verify')

]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class Add2CartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, widget=forms.NumberInput(), label='تعداد')

cart/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from cart.forms import Add2CartForm
from cart.utils.cart import Cart
from shop.models import Product


def detail(request):
    cart = Cart(request)
    return render(request, template_name='cart/detail.html', context={'cart': cart})


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        form = Add2CartForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            cart.add(product=product, quantity=data['quantity'])
            messages.success(request, 'محصول به سبد شما اضافه شد.', 'success')
    elif request.method == 'GET':
        cart.add(product=product, quantity=1)
        messages.success(request, 'محصول به سبد شما اضافه شد.', 'success')
    ref = request.META.get('HTTP_REFERER')
    if ref:
        return redirect(ref)
    return redirect('cart:detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    messages.success(request, 'محصول از سبد شما حذف شد.', 'success')
    return redirect('cart:detail')


def cart_minus(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if cart.cart[str(product_id)]['quantity'] - 1 <= 0:
        cart.remove(product)
        return redirect('cart:detail')
    cart.add(product, -1)
    return redirect('cart:detail')


def cart_plus(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product, 1)
    return redirect('cart:detail')

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block extra_css %}
    <link rel="stylesheet" href="/static/css/cart_detail.css">
{% endblock %}

{% block content %}

    <section class="h-100 h-custom" style="background-color: #afd5ff;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12">
                    <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                        <div class="card-body p-0">
                            <div class="row g-0">
                                <div class="col-lg-8">
                                    <div class="p-5">
                                        <div class="d-flex justify-content-between align-items-center mb-5">
                                            <h1 class="fw-bold mb-0 text-black">سبد خرید</h1>
                                            <h6 class="mb-0 text-muted">تعداد آیتم ها {{ cart.size_cart }}</h6>
                                        </div>
                                        <hr class="my-4">

                                        {% for item in cart %}
                                            <div class="row mb-4 d-flex justify-content-between align-items-center">
                                                <div class="col-md-2 col-lg-2 col-xl-2">
                                                    <img
                                                            src="{{ item.product.image.url }}"
                                                            class="img-fluid rounded-3" alt="Cotton T-shirt">
                                                </div>
                                                <div class="col-md-3 col-lg-3 col-xl-3">
                                                    <h3 class="text-black mb-0">{{ item.product.name }}</h3>
                                                </div>
                                                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                                    <a href="{% url 'cart:cart_minus' item.product.id %}">
                                                        <button class="btn btn-link px-2"><i class="fa fa-minus"></i>
                                                        </button>
                                                    </a>

                                                    <input id="form1" min="0" name="quantity"
                                                           value="{{ item.quantity }}" type="number"
                                                           class="form-control form-control-sm"/>

                                                    <a href="{% url 'cart:cart_plus' item.product.id %}">
                                                        <button class="btn btn-link px-2"><i class="fa fa-plus"></i>
                                                        </button>
                                                    </a>
                                                </div>
                                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                    <h6 class="mb-0">قیمت واحد= {{ item.price }} تومان </h6>
                                                    <h6 class="mb-0">مجموع قیمت= {{ item.total_price }} تومان </h6>
                                                </div>
                                                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                                    <a href="{% url 'cart:cart_remove' item.product.id %}"
                                                       class="text-muted"><i class="fa fa-times"></i></a>
                                                </div>
                                            </div>

                                            <hr class="my-4">
                                        {% endfor %}

                                        <div class="pt-5">
                                            <h6 class="mb-0"><a href="{% url 'shop:index' %}" class="text-body"><i
                                                    class="fas fa-long-arrow-alt-left me-2"></i>بازگشت به صفحه اصلی</a>
                                            </h6>
                                        </div>
                                        <div class="pt-5">
                                            <h4 class="mb-0"><a href="{% url 'accounts:create_Address' %}"
                                                                class="text-body"><i
                                                    class="fas fa-long-arrow-alt-left me-2"></i>ساختن یک آدرس جدید</a>
                                            </h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 bg-grey" dir="rtl">
                                    <div class="p-5">
                                        <h3 class="fw-bold mb-5 mt-2 pt-1">خلاصه سبد</h3>
                                        <hr class="my-4">

                                        <div class="d-flex justify-content-between mb-4">
                                            <h5 class="text-uppercase">تعداد آیتم ها: {{ cart.size_cart }} </h5>
                                        </div>

                                        <hr class="my-4">

                                        <div class="d-flex justify-content-between mb-4">
                                            <h5>مجموع قیمت کل سبد (تومان): </h5>
                                            <h5 id="cart_total_price">{{ cart.get_total_price }}</h5>
                                        </div>

                                        <hr class="my-4">

                                        <div class="d-flex justify-content-between mb-4">
                                            <h7> خرید بالای ۳۹۰ هزار تومان هزینه پست رایگان است</h7>
                                        </div>
                                        <p style="background-color:Tomato;"><b> به علت گرمی هوا فعلا در شهر
                                            تهران میتوانیم ارسال کنیم</b></p>

                                        <form action="{% url 'order:order_create' %}" method="post">
                                            {% csrf_token %}
                                            <div class="d-flex justify-content-between mb-4">
                                                <h7></h7>
                                                <h5>هزینه پست: </h5>

                                                {% if cart.get_total_price >= 390000 %}
                                                    رایگان
                                                {% else %}
                                                    <div class="form-check">
                                                        <input class="form-check-input" type="radio" name="post_method"
                                                               id="post_tehran" checked value="post_tehran"
                                                               onclick="updatePrice()">
                                                        <label class="form-check-label" for="post_tehran">
                                                            استان تهران: ۳۵ هزار تومان
                                                        </label>
                                                    </div>
                                                    {#                                                    <div class="form-check">#}
                                                    {#                                                        <input class="form-check-input" type="radio" name="post_method"#}
                                                    {#                                                               id="post_other" value="post_other" checked onclick="updatePrice()">#}
                                                    {#                                                        <label class="form-check-label" for="post_other">#}
                                                    {#                                                            بقیه شهر‌ها: ۳۰ هزار تومان#}
                                                    {#                                                        </label>#}
                                                    {#                                                    </div>#}
                                                {% endif %}
                                            </div>
                                            <hr class="my-4">

                                            <div class="d-flex justify-content-between mb-5">
                                                <h3 class="text-uppercase">قیمت نهایی (تومان)</h3>
                                                {% if cart.get_total_price >= 390000 %}
                                                    <h5 id="final_price">{{ cart.get_total_price }}</h5>
                                                {% else %}
                                                    <h5 id="final_price">{{ cart.get_total_price|add:35000 }}</h5>
                                                {% endif %}
                                            </div>

                                            <input type="submit" class="btn btn-dark btn-block btn-lg"
                                                   value="ساخت فاکتور و پرداخت">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="/static/js/cart_update_price.js"></script>
{% endblock %}