accounts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('address/', login_required(views.AddressListView.as_view()), name='address_list'),
    path('address/<int:pk>/', login_required(views.AddressDetailView.as_view()), name='address_detail'),
    path('address/create', views.create_address, name='create_Address'),
    path('password-reset/', views.CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-done/',
         views.CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/',
         views.CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('address/delete/<int:pk>/', views.delete_address, name="delete_address"),
    path('address/edit/<int:pk>/', views.edit_address, name='edit_address'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('minus/<int:product_id>/', views.cart_minus, name='cart_minus'),
    path('plus/<int:product_id>/', views.cart_plus, name='cart_plus'),
]

onlineShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('delivery/', include('delivery.urls')),
    path('', include('django_prometheus.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import MyUserManager


class MyUser(AbstractUser):
    username = None
    email = models.EmailField(
        unique=True,
        error_messages={
            'unique': "A user with that email already exists.",
        },
    )
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(
        max_length=11, unique=True, error_messages={
            'unique': "A user with that phone number already exists."
        })
    is_delivery_man = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone_number']

    def __str__(self):
        return self.email

    def get_size_address(self):
        return len(self.address.all())

    def get_size_open_orders(self):
        return len(self.orders.all().filter(is_paid=False))


class UserAddress(models.Model):
    name = models.CharField(max_length=30, default="خانه")
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='address')
    zip_code = models.CharField(max_length=10)
    address_text = models.CharField(max_length=100)
    name_of_transferee = models.CharField(max_length=20)
    phone_of_transferee = models.CharField(max_length=15)
    state = models.CharField(max_length=30, default='تهران')
    city = models.CharField(max_length=30, default='تهران')

    def __str__(self):
        return self.name

accounts/forms.py
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django import forms
from .models import MyUser, UserAddress


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('email', 'first_name', 'last_name', 'phone_number', 'is_delivery_man')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise forms.ValidationError('passwords must match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ('email', 'password', 'first_name', 'last_name', 'phone_number', 'is_delivery_man')

    def clean_password(self):
        return self.initial['password']


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput())
    password = forms.CharField(widget=forms.PasswordInput())


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(), label='ایمیل')
    first_name = forms.CharField(widget=forms.TextInput(), max_length=20, label='نام')
    last_name = forms.CharField(widget=forms.TextInput(), max_length=20, label='نام خانوادگی')
    phone_number = forms.CharField(max_length=11, widget=forms.TextInput(), label='تلفن همراه')
    password1 = forms.CharField(widget=forms.PasswordInput(), label='رمز')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='تکرار رمز')


class ChoiceUserAddressForm(forms.Form):
    address = forms.ChoiceField(choices=(), label="آدرس")

    def __init__(self, user, *args, **kwargs):
        super(ChoiceUserAddressForm, self).__init__(*args, **kwargs)
        valid_address = UserAddress.objects.filter(user=user)
        self.fields['address'].choices = [(address.id, address) for address in valid_address]


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = UserAddress
        exclude = ('user',)
        labels = {
            'name': 'اسم آدرس',
            'zip_code': 'کد پستی',
            'address_text': 'آدرس',
            'name_of_transferee': 'نام دریافت کننده',
            'phone_of_transferee': 'شماره دریافت کننده',
            'state': 'استان',
            'city': 'شهر',
        }

    def __init__(self, *args, **kwargs):
        super(UserAddressForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.initial['name'] = self.instance.name
            self.initial['zip_code'] = self.instance.zip_code
            self.initial['address_text'] = self.instance.address_text
            self.initial['name_of_transferee'] = self.instance.name_of_transferee
            self.initial['phone_of_transferee'] = self.instance.phone_of_transferee
            self.initial['state'] = self.instance.state
            self.initial['city'] = self.instance.city

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from accounts.forms import UserLoginForm, UserRegistrationForm, UserAddressForm
from accounts.models import MyUser
from django.views import generic
from .models import UserAddress
from django.contrib.auth.decorators import login_required
from accounts import email_service
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView
from django.urls import reverse_lazy


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request, email=data['email'], password=data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'با موفقیت وارد شدید', 'success')
                nxt = request.GET.get("next", None)
                if nxt:
                    if nxt == '/order/create/':
                        return redirect('cart:detail')
                    return redirect(nxt)
                return redirect('shop:index')
            else:
                messages.error(request, 'ایمیل یا رمز اشتباه است', 'danger')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'با موفقیت خارج شدید', 'success')
    return redirect('shop:index')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if data['password1'] and data['password2'] and data['password1'] == data['password2']:
                user = MyUser.objects.create_user(email=data['email'], password=data['password1'],
                                                  first_name=data['first_name'], last_name=data['last_name'],
                                                  phone_number=data['phone_number'], )
                login(request, user)
                messages.success(request, 'با موفقیت ثبت نام شدید', 'success')
                email_service.welcome_email_new_user.delay(user.email, user.first_name)
                return redirect('shop:index')
            else:
                messages.error(request, 'رمز ها یکسان نیستند', 'danger')

    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})


class AddressListView(generic.ListView):
    context_object_name = 'addresses'
    template_name = 'accounts/address_list.html'

    def get_queryset(self):
        return UserAddress.objects.filter(user=self.request.user)


class AddressDetailView(generic.DetailView):
    context_object_name = 'address'
    template_name = 'accounts/address_detail.html'

    def get_queryset(self):
        return UserAddress.objects.filter(user=self.request.user)


@login_required()
def create_address(request):
    if request.method == 'POST':
        if request.user.get_size_address() >= 5:
            messages.error(request, 'نمی توان بیشتر از ۵ تا آدرس ساخت', 'danger')
            return redirect('accounts:address_list')
        form = UserAddressForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            address = UserAddress.objects.create(user=request.user, name=data['name'],
                                                 name_of_transferee=data['name_of_transferee'],
                                                 phone_of_transferee=data['phone_of_transferee'], city=data['city'],
                                                 state=data['state'], address_text=data['address_text'],
                                                 zip_code=data['zip_code'])
            address.save()
            messages.success(request, 'آدرس با موفقیت ساخته شد.', 'success')
            return redirect('accounts:address_list')

    else:
        form = UserAddressForm()
    return render(request, 'accounts/address_create.html', {'form': form})


class CustomPasswordResetView(PasswordResetView):
    email_template_name = 'accounts/email_templates/password_reset_email.html'
    template_name = 'accounts/password_reset.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


@login_required()
def delete_address(request, pk):
    address = get_object_or_404(UserAddress, pk=pk)
    if address.user != request.user:
        raise Http404
    address.delete()
    messages.success(request, "آدرس با موفقیت حذف شد")
    return redirect('accounts:address_list')


@login_required()
def edit_address(request, pk):
    address = get_object_or_404(UserAddress, pk=pk)
    if request.user != address.user:
        raise Http404
    if request.method == 'POST':
        form = UserAddressForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            address.name = data['name']
            address.zip_code = data['zip_code']
            address.name_of_transferee = data['name_of_transferee']
            address.phone_of_transferee = data['phone_of_transferee']
            address.address_text = data['address_text']
            address.state = data['state']
            address.city = data['city']
            address.save()
            messages.success(request, "آدرس با موفقیت ویرایش شد")
            return redirect('accounts:address_list')

    return render(request, 'accounts/address_edit.html', {'address': address})

accounts/templates/accounts/address_create.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="/static/img/login_img.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <div dir="rtl">

                        <div class="divider d-flex align-items-center my-4">
                            <img class="center-block" src="/static/img/logo-j.jpg">
                        </div>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_name">اسم آدرس</label>
                                <input type="text" id="id_name" name="name" class="form-control form-control-lg"
                                       placeholder="برای مثال: خانه" maxlength="30" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_zip_code">کد پستی</label>
                                <input type="text" id="id_zip_code" name="zip_code" class="form-control form-control-lg"
                                       placeholder="کد ۱۰ رقمی پستی" maxlength="10" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_address_text">آدرس</label>
                                <input type="text" id="id_address_text" name="address_text"
                                       class="form-control form-control-lg"
                                       placeholder="آدرس خود را دقیق وارد کنید" maxlength="100" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_name_of_transferee">نام دریافت کننده</label>
                                <input type="text" id="id_name_of_transferee" name="name_of_transferee"
                                       class="form-control form-control-lg"
                                       maxlength="20" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_phone_of_transferee">تلفن همراه دریافت کننده</label>
                                <input type="text" id="id_phone_of_transferee" name="phone_of_transferee"
                                       class="form-control form-control-lg"
                                       placeholder="برای مثال: ۰۹۱۲۱۲۳۴۵۶۷" maxlength="11" required/>
                            </div>

                            <p style="background-color:Tomato;"> <b> به علت گرمی هوا فعلا در شهر تهران میتوانیم ارسال کنیم</b></p>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_state">استان</label>
                                <input type="text" id="id_state" name="state" class="form-control form-control-lg"
                                       maxlength="30" value="تهران" readonly required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_city">شهر</label>
                                <input type="text" id="id_city" name="city" class="form-control form-control-lg"
                                       maxlength="30" value="تهران" readonly required/>
                            </div>

                            <input type="submit" class="btn btn-primary" value="ساخت آدرس">
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </section>

{% endblock %}

accounts/templates/accounts/address_edit.html
{% extends 'base.html' %}

{% block content %}
    <section >
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="/static/img/login_img.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <div dir="rtl">

                        <div class="divider d-flex align-items-center my-4">
                            <img class="center-block" src="/static/img/logo-j.jpg">
                        </div>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_name">اسم آدرس</label>
                                <input type="text" id="id_name" name="name" class="form-control form-control-lg"
                                       value="{{ address.name }}" maxlength="30" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_zip_code">کد پستی</label>
                                <input type="text" id="id_zip_code" name="zip_code" class="form-control form-control-lg"
                                       value="{{ address.zip_code }}" maxlength="10" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_address_text">آدرس</label>
                                <input type="text" id="id_address_text" name="address_text" class="form-control form-control-lg"
                                       value="{{ address.address_text }}" maxlength="100" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_name_of_transferee">نام دریافت کننده</label>
                                <input type="text" id="id_name_of_transferee" name="name_of_transferee" class="form-control form-control-lg"
                                        value="{{ address.name_of_transferee }}" maxlength="20" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_phone_of_transferee">تلفن همراه دریافت کننده</label>
                                <input type="text" id="id_phone_of_transferee" name="phone_of_transferee" class="form-control form-control-lg"
                                        value="{{ address.phone_of_transferee }}" maxlength="11" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_state">استان</label>
                                <input type="text" id="id_state" name="state" class="form-control form-control-lg"
                                       value="{{ address.state }}" readonly maxlength="30" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_city">شهر</label>
                                <input type="text" id="id_city" name="city" class="form-control form-control-lg"
                                       value="{{ address.city }}" readonly maxlength="30" required/>
                            </div>

                            <input type="submit" class="btn btn-primary" value="ویرایش آدرس">
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </section>

{% endblock %}>

accounts/templates/accounts/address_list.html
{% extends 'base.html' %}

{% block extra_css %}
    <link rel="stylesheet" href="/static/css/list.css">
{% endblock %}

{% block content %}
    <div class="event-schedule-area-two bg-color pad100">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title text-center">
                        <div class="title-text">
                            <h2>لیست آدرس های شما</h2>
                        </div>
                        <p>
                            در این قسمت میتوانید همه‌ی آدرس های خود را ببینید<br/>
                            یا ویرایش یا حذف کنید
                        </p>
                    </div>
                </div>
                <!-- /.col end-->
            </div>
            <!-- row end-->
            <div class="row">
                <div class="col-lg-12">
                    {#                    <ul class="nav custom-tab" id="myTab" role="tablist">#}
                    {#                        <li class="nav-item">#}
                    {#                            <a class="nav-link active show" id="home-taThursday" data-toggle="tab" href="#home"#}
                    {#                               role="tab" aria-controls="home" aria-selected="true">Day 1</a>#}
                    {#                        </li>#}
                    {#                        <li class="nav-item">#}
                    {#                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"#}
                    {#                               aria-controls="profile" aria-selected="false">Day 2</a>#}
                    {#                        </li>#}
                    {#                        <li class="nav-item">#}
                    {#                            <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab"#}
                    {#                               aria-controls="contact" aria-selected="false">Day 3</a>#}
                    {#                        </li>#}
                    {#                        <li class="nav-item d-none d-lg-block">#}
                    {#                            <a class="nav-link" id="sunday-tab" data-toggle="tab" href="#sunday" role="tab"#}
                    {#                               aria-controls="sunday" aria-selected="false">Day 4</a>#}
                    {#                        </li>#}
                    {#                        <li class="nav-item mr-0 d-none d-lg-block">#}
                    {#                            <a class="nav-link" id="monday-tab" data-toggle="tab" href="#monday" role="tab"#}
                    {#                               aria-controls="monday" aria-selected="false">Day 5</a>#}
                    {#                        </li>#}
                    {#                    </ul>#}
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade active show" id="home" role="tabpanel">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">اسم آدرس</th>
                                        <th scope="col">نام تحویل گیرنده</th>
                                        <th scope="col">شماره همراه تحویل گیرنده</th>
                                        <th scope="col">جزيیات</th>
                                        <th scope="col">حذف آدرس</th>
                                        <th scope="col">ویرایش آدرس</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for address in addresses %}
                                        <tr class="inner-box">
                                            <th scope="row">
                                                <span>{{ forloop.counter }}</span>
                                            </th>
                                            <td>
                                                <div class="event-wrap"> {{ address.name }}</div>
                                            </td>
                                            <td>
                                                <div class="event-wrap"> {{ address.name_of_transferee }} </div>
                                            </td>
                                            <td>
                                                <div class="event-wrap"> {{ address.phone_of_transferee }} </div>
                                            </td>
                                            <td>
                                                <div class="primary-btn">
                                                    <a class="btn btn-primary"
                                                       href="{% url 'accounts:address_detail' address.id %}">جزئیات</a>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="primary-btn">
                                                    <a class="btn btn-primary"
                                                       href="{% url 'accounts:delete_address' address.id %}">حذف</a>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="primary-btn">
                                                    <a class="btn btn-primary"
                                                       href="{% url 'accounts:edit_address' address.id %}">ویرایش
                                                        آدرس</a>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /col end-->
            </div>
            <!-- /row end-->
            <div class="primary-btn">
                <a class="btn btn-primary" href="{% url 'accounts:create_Address' %}">ساخت آدرس جدید</a>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
<p>رمز شما با موفقیت عوض شد &#128525; &#128525; &#128525; </p>

<p><a href={% url 'accounts:login' %}>صفحه ورود</a></p>

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <section >
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="/static/img/login_img.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <div>

                        <div class="divider d-flex align-items-center my-4">
                            <img class="center-block" src="/static/img/logo-j.jpg">
                        </div>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_email">ایمیل</label>
                                <input type="email" id="id_email" name="email" class="form-control form-control-lg"
                                       placeholder="ایمیل خود را وارد کنید" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_first_name">نام</label>
                                <input type="text" id="id_first_name" name="first_name" class="form-control form-control-lg"
                                       placeholder="نام خود را وارد کنید" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_last_name" >نام خانوادگی</label>
                                <input type="text" id="id_last_name" name="last_name" class="form-control form-control-lg"
                                       placeholder="نام خانوادگی خود را وارد کنید" required/>
                            </div>

                            <div class="form-outline mb-4">
                                <label class="form-label" for="id_phone_number" >تلفن همراه</label>
                                <input type="text" id="id_phone_number" name="phone_number" class="form-control form-control-lg"
                                       placeholder="مثال: ۰۹۱۲۱۲۳۴۵۶۷" required/>
                            </div>

                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_password1">رمز</label>
                                <input type="password" id="id_password1" name="password1"
                                       class="form-control form-control-lg"
                                       placeholder="رمز خود را وارد کنید" required/>
                            </div>

                            <div class="form-outline mb-3">
                                <label class="form-label" for="id_password2">تکرار رمز</label>
                                <input type="password" id="id_password2" name="password2"
                                       class="form-control form-control-lg"
                                       placeholder="رمز خود را تکرار کنید" required/>
                            </div>

                            <input type="submit" class="btn btn-primary" value="ثبت نام">
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </section>

{% endblock %}