accounts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('address/', login_required(views.AddressListView.as_view()), name='address_list'),
    path('address/<int:pk>/', login_required(views.AddressDetailView.as_view()), name='address_detail'),
    path('address/create', views.create_address, name='create_Address'),
    path('password-reset/', views.CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-done/',
         views.CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/',
         views.CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('address/delete/<int:pk>/', views.delete_address, name="delete_address"),
    path('address/edit/<int:pk>/', views.edit_address, name='edit_address'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('minus/<int:product_id>/', views.cart_minus, name='cart_minus'),
    path('plus/<int:product_id>/', views.cart_plus, name='cart_plus'),
]

onlineShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('delivery/', include('delivery.urls')),
    path('', include('django_prometheus.urls')),

]

order/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', login_required(views.order_create), name='order_create'),
    path('<int:pk>/', login_required(views.OrderDetailView.as_view()), name='detail'),
    path('', login_required(views.OrderListView.as_view()), name='order_list'),
    path('payment/<int:order_id>/', views.payment, name='payment'),
    path('delete/<int:pk>', views.delete_order, name='delete_order'),
    path('verify/', views.verify, name='verify')

]

order/models.py
from django.db import models
from django.conf import settings
# from django.core.validators import MinValueValidator, MaxValueValidator
from shop.models import Product
from django.utils import timezone
from accounts.models import UserAddress


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders')
    created = models.DateTimeField(default=timezone.now)
    is_paid = models.BooleanField(default=False)
    address = models.ForeignKey(UserAddress, related_name='order_addresses', on_delete=models.SET_NULL, null=True)
    authority = models.CharField(max_length=100, null=True)
    post_cost = models.IntegerField(default=0)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"{self.user} - {self.id}"

    @property
    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all()) + self.post_cost
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.SmallIntegerField(default=1)

    def __str__(self):
        return str(self.order.user) + str(self.product)

    def get_cost(self):
        return self.product.get_final_price() * self.quantity

order/forms.py
from django import forms
from accounts.models import UserAddress
from order.models import Order

order/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views import generic
from delivery.views import create_delivery_pack
from accounts.models import UserAddress
from cart.utils.cart import Cart
from order.models import Order, OrderItem
from django.views.decorators.http import require_POST
from order.sms_service import send_sms_success_payment
from .zarinpal import send_request, verify_pay


@require_POST
def order_create(request):
    cart = Cart(request)
    if cart.size_cart() == 0:
        messages.error(request, 'سبد شما خالی است', 'danger')
        return redirect('cart:detail')
    if request.user.get_size_open_orders() >= 5:
        messages.error(request, 'نمی توان بیشتر از ۵ تا سفارش باز داشت', 'danger')
        return redirect('order:order_list')
    order = Order.objects.create(user=request.user)
    if cart.get_total_price() < 390000:
        order.post_cost = 35000
        # order.post_cost = 20000 if request.POST['post_method'] == 'post_tehran' else 30000
        order.save()
    for item in cart:
        OrderItem.objects.create(order=order, product=item['product'], quantity=item['quantity'])
    cart.clear()
    messages.success(request, 'فاکتور شما ساخته شد و آماده پرداخت می باشد.', 'success')
    return redirect('order:order_list')


class OrderDetailView(generic.DetailView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_paid=False)


class OrderListView(generic.ListView):
    context_object_name = 'orders'
    template_name = 'order/order_list.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_paid=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['addresses'] = self.request.user.address.all()
        return context


@login_required()
def payment(request, order_id):
    if request.method != 'POST':
        raise Http404
    order = get_object_or_404(Order, pk=order_id)
    if order.user != request.user:
        raise Http404
    if 'address' not in request.POST:
        messages.error(request, 'آدرس باید انتخاب شود', 'danger')
        return redirect('order:order_list')
    address = get_object_or_404(UserAddress, pk=request.POST['address'])
    response = send_request(order.get_total_price, f"{request.user.last_name} سفارش ")
    if response['status']:
        order.authority = response['authority']
        order.address = address
        order.save()
        return redirect(response['url'])
    messages.error(request, 'پرداخت با موفقیت انجام نشد لطفا دوباره تلاش کنید', 'danger')
    print(response['code'])
    return redirect('order:order_list')
    # order.is_paid = True
    # create_delivery_pack(order)
    # send_sms_success_payment.delay(order.address.phone_of_transferee, order.address.name_of_transferee)
    # context = {'user': request.user, 'price': order.get_total_price, 'address': request.POST['address']}
    # return render(request, 'order/payment.html', context)


def verify(request):
    if 'Authority' not in request.GET:
        raise Http404
    auth = request.GET['Authority']
    order = get_object_or_404(Order, authority=auth)
    response = verify_pay(auth, order.get_total_price)
    if response['status']:
        order.is_paid = True
        order.save()
        create_delivery_pack(order, response['RefID'])
        send_sms_success_payment.delay(order.address.phone_of_transferee, order.address.name_of_transferee)
    else:
        print(response['code'])
    return redirect('delivery:customer_list')


@login_required()
def delete_order(request, pk):
    order = get_object_or_404(Order, pk=pk)
    if order.user != request.user:
        raise Http404
    if order.is_paid:
        messages.error(request, 'نمی توان سفارش پرداخت شده را حذف کرد', 'danger')
        return redirect('order:order_list')
    order.delete()
    messages.success(request, "سفارش با موفقیت حذف شد")
    return redirect('order:order_list')

order/templates/order/order_detail.html
{% extends 'base.html' %}

{% block extra_css %}
    <link rel="stylesheet" href="/static/css/factor.css">
{% endblock %}

{% block content %}
    <section style="min-height: 500px">
        <h2>محصولات</h2>

        <table>
            <tr>
                <th>#</th>
                <th>نام محصول</th>
                <td>قیمت(تومان)</td>
                <td>تعداد</td>
                <td>قیمت کل(تومان)</td>
            </tr>
            {% for item in order.items.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.product.get_final_price }}</td>
                    <td> {{ item.quantity }} </td>
                    <td> {{ item.get_cost }} </td>
                </tr>
            {% endfor %}

            <tr>
                <td>هزینه پست (تومان)</td>
                <td>{{ order.post_cost }}</td>
            </tr>
            <tr>
                <td>قیمت کل سفارش (تومان)</td>
                <td>{{ order.get_total_price }}</td>
            </tr>
        </table>

    </section>


{% endblock %}

order/templates/order/order_list.html
{% extends 'base.html' %}

{% block extra_css %}
    <link rel="stylesheet" href="/static/css/list.css">
{% endblock %}

{% block content %}
    <div class="event-schedule-area-two bg-color pad100">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title text-center">
                        <div class="title-text">
                            <h2>لیست سفارش های شما</h2>
                        </div>
                        <p>
                            اگر آدرسی ندارید پایین صفحه ساخت آدرس را کلیک کنید <br/>
                            بعد از ساخت آدرس صفحه را دوباره بارگزاری کنید
                        </p>
                    </div>
                </div>
                <!-- /.col end-->
            </div>
            <!-- row end-->
            <div class="row">
                <div class="col-lg-12">
                    {#                    <ul class="nav custom-tab" id="myTab" role="tablist">#}
                    {#                        <li class="nav-item">#}
                    {#                            <a class="nav-link active show" id="home-taThursday" data-toggle="tab" href="#home"#}
                    {#                               role="tab" aria-controls="home" aria-selected="true">Day 1</a>#}
                    {#                        </li>#}
                    {#                        <li class="nav-item">#}
                    {#                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"#}
                    {#                               aria-controls="profile" aria-selected="false">Day 2</a>#}
                    {#                        </li>#}
                    {#                        <li class="nav-item">#}
                    {#                            <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab"#}
                    {#                               aria-controls="contact" aria-selected="false">Day 3</a>#}
                    {#                        </li>#}
                    {#                        <li class="nav-item d-none d-lg-block">#}
                    {#                            <a class="nav-link" id="sunday-tab" data-toggle="tab" href="#sunday" role="tab"#}
                    {#                               aria-controls="sunday" aria-selected="false">Day 4</a>#}
                    {#                        </li>#}
                    {#                        <li class="nav-item mr-0 d-none d-lg-block">#}
                    {#                            <a class="nav-link" id="monday-tab" data-toggle="tab" href="#monday" role="tab"#}
                    {#                               aria-controls="monday" aria-selected="false">Day 5</a>#}
                    {#                        </li>#}
                    {#                    </ul>#}
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade active show" id="home" role="tabpanel">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">تاریخ ساخت</th>
                                        <th scope="col">قیمت کل(تومان)</th>
                                        <th scope="col">جزئیات سفارش</th>
                                        <th scope="col">آدرس</th>
                                        <th scope="col">پرداخت</th>
                                        <th scope="col">حذف سفارش</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for order in orders %}
                                        <tr class="inner-box">
                                            <th scope="row">
                                                <span>{{ forloop.counter }}</span>
                                            </th>
                                            <td>
                                                <div class="event-wrap"> {{ order.created }}</div>
                                            </td>
                                            <td>
                                                <div class="event-wrap"> {{ order.get_total_price }} </div>
                                            </td>
                                            <td>
                                                <div class="event-wrap"> <a href="{% url 'order:detail' order.id %}">جزئیات</a> </div>
                                            </td>
                                            <form action="{% url 'order:payment' order.id %}" method="post">
                                                {% csrf_token %}
                                                <td><select name="address">
                                                    {% for address in addresses %}
                                                        <option value="{{ address.id }}">{{ address.name }}</option>
                                                    {% endfor %}
                                                </select></td>
                                                <td><input type="submit" class="btn btn-primary" value="پرداخت"></td>
                                            </form>
                                            <td><a class="btn btn-primary" href="{% url 'order:delete_order' order.id %}">حذف</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /col end-->
            </div>
            <!-- /row end-->
            <div class="primary-btn">
                <a target="_blank" class="btn btn-primary" href="{% url 'accounts:create_Address' %}">ساخت آدرس جدید</a>
            </div>
        </div>
    </div>
{% endblock %}

order/templates/order/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {{ user }}
    {{ price }}
    {{ address }}
</body>
</html>