accounts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('address/', login_required(views.AddressListView.as_view()), name='address_list'),
    path('address/<int:pk>/', login_required(views.AddressDetailView.as_view()), name='address_detail'),
    path('address/create', views.create_address, name='create_Address'),
    path('password-reset/', views.CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-done/',
         views.CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/',
         views.CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('address/delete/<int:pk>/', views.delete_address, name="delete_address"),
    path('address/edit/<int:pk>/', views.edit_address, name='edit_address'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('minus/<int:product_id>/', views.cart_minus, name='cart_minus'),
    path('plus/<int:product_id>/', views.cart_plus, name='cart_plus'),
]

delivery/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'delivery'

urlpatterns = [
    path('list/', login_required(views.PostDeliveryPackListView.as_view()), name='post_list'),
    path('<int:pk>/', login_required(views.delivery_pack_detail), name='detail'),
    path('list-c/', login_required(views.CustomerDeliveryPackListView.as_view()), name='customer_list'),
    path('c/<int:pk>/', login_required(views.CustomerPackDetailView.as_view()), name='customer_detail'),
]

onlineShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('delivery/', include('delivery.urls')),
    path('', include('django_prometheus.urls')),

]

order/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', login_required(views.order_create), name='order_create'),
    path('<int:pk>/', login_required(views.OrderDetailView.as_view()), name='detail'),
    path('', login_required(views.OrderListView.as_view()), name='order_list'),
    path('payment/<int:order_id>/', views.payment, name='payment'),
    path('delete/<int:pk>', views.delete_order, name='delete_order'),
    path('verify/', views.verify, name='verify')

]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Telond</title>
    <link rel="icon" href="/static/img/favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet'
          type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/static/css/owl.carousel.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/responsive.css">

    {% block extra_css %}
    {% endblock %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="header-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="user-menu">
                    <ul>
                        <li><a href="{% url 'shop:index' %}"><i class="fa fa-sign-out"></i> صفحه اصلی</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> خروج از حساب کاربری</a>
                            </li>
                            <li><a href="{% url 'accounts:address_list' %}"><i class="fa fa-list-ul"
                                                                               aria-hidden="true"></i>آدرس های من</a>
                            </li>
                            <li><a href="{% url 'order:order_list' %}"><i class="fa fa-list"></i>سفارش های باز من</a>
                            </li>
                            <li><a href="{% url 'delivery:customer_list' %}"><i class="fa fa-list"></i>سفارش های پرداخت
                                شده من</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}"><i class="fa fa-sign-in"></i> وارد یا ساخت حساب</a>
                            </li>
                        {% endif %}
                        <li><a href="{% url 'cart:detail' %}"><i class="fa fa-shopping-cart"></i> سبد خرید من</a></li>

                    </ul>
                </div>
            </div>

            {#                    <div class="col-md-4">#}
            {#                        <div class="header-right">#}
            {#                            <ul class="list-unstyled list-inline">#}
            {#                                <li class="dropdown dropdown-small">#}
            {#                                    <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">currency :</span><span class="value">USD </span><b class="caret"></b></a>#}
            {#                                    <ul class="dropdown-menu">#}
            {#                                        <li><a href="#">USD</a></li>#}
            {#                                        <li><a href="#">INR</a></li>#}
            {#                                        <li><a href="#">GBP</a></li>#}
            {#                                    </ul>#}
            {#                                </li>#}
            {#    #}
            {#                                <li class="dropdown dropdown-small">#}
            {#                                    <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">language :</span><span class="value">English </span><b class="caret"></b></a>#}
            {#                                    <ul class="dropdown-menu">#}
            {#                                        <li><a href="#">English</a></li>#}
            {#                                        <li><a href="#">French</a></li>#}
            {#                                        <li><a href="#">German</a></li>#}
            {#                                    </ul>#}
            {#                                </li>#}
            {#                            </ul>#}
            {#                        </div>#}
            {#                    </div>#}
        </div>
    </div>
</div> <!-- End header area -->

{% include 'messages.html' %}
<div class="app__content">
    {% block content %}{% endblock content %}
</div>

<div class="footer-top-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="footer-about-us">
                    <h2><span>فروشگاه تلوند </span></h2>
                    <p>درسال ۱۴۰۲ تاسیس شده است و هم اکنون در تلاش است تا بهترین کیفیت همراه با مناسب ترین قیمت را برای شما مشتریان عزیز عرضه کند.
فروشگاه تلوند دسترسی شما را برای انواع شکلات های خارجی به صورت یک جا فراهم کرده است تا خریدی اسان و خوشمزه در هر زمان و هر مکان داشته باشید.</p>
                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-menu">
                    <h2 class="footer-wid-title">تماس با ما </h2>
                    <div class="footer-social">
                        <p> پشتیبانی سایت و سفارشات شما در تلگرام </p>
                        <span> @telond_ir <a href="https://t.me/telond_ir" target="_blank"><i
                                class="fa fa-telegram"></i></a> </span>
                        <br><br>
                        <p> صفحه ما در اینستاگرام</p>
                        <span> @telond.ir <a href="https://instagram.com/telond.ir?igshid=NTc4MTIwNjQ2YQ==" target="_blank"><i
                                class="fa fa-instagram"></i></a> </span>
                    </div>

                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-menu">
                    <script src="https://www.zarinpal.com/webservice/TrustCode" type="text/javascript"></script>
                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-newsletter">
                    <h2 class="footer-wid-title">توجه</h2>
                    <p>کلیه محتوای معنوی و مادی این سایت متعلق به سایت <a href="https://telond.ir">تلوند</a> میباشد و
                        هرگونه استفاده و كپي برداري تحت پيگرد قانوني قرار خوهد گرفت. </p>

                </div>
            </div>
        </div>
    </div>
</div> <!-- End footer top area -->

<!-- Latest jQuery form server -->
<script src="https://code.jquery.com/jquery.min.js"></script>

<!-- Bootstrap JS form CDN -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<!-- jQuery sticky menu -->
<script src="/static/js/owl.carousel.min.js"></script>
<script src="/static/js/jquery.sticky.js"></script>

<!-- jQuery easing -->
<script src="/static/js/jquery.easing.1.3.min.js"></script>

<!-- Main Script -->
<script src="/static/js/main.js"></script>

<!-- Slider -->
<script type="text/javascript" src="/static/js/bxslider.min.js"></script>
<script type="text/javascript" src="/static/js/script.slider.js"></script>
</body>

templates/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            {% if 'danger' in message.tags %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif 'success' in message.tags %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </ul>
{% endif %}